FROM mcr.microsoft.com/mssql/server:2019-latest

USER root
RUN mkdir -p /opt/mssql-scripts
COPY ./millerTimeCreateScript.sql /opt/mssql-scripts

ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=!mill3rLoc@l
ENV MSSQL_TCP_PORT=1433
ENV MSSQL_PID=Developer

CMD /bin/bash -c '(/opt/mssql/bin/sqlservr & sleep 20s & wait) && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "!mill3rLoc@l" -i /opt/mssql-scripts/millerTimeCreateScript.sql'
